import playwright.async_api
import playwright.sync_api

async def async_apply(playwright: playwright.async_api.Playwright) -> None: ...
def sync_apply(playwright: playwright.sync_api.Playwright) -> None: ...
